<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'id' => 1,
                'user_id' => 1,
                'category_id' => 1,
                'title' => 'I Have A Dream',
                'author' => 'Arif Rahman Lubis',
                'publisher' => 'Qultum Media',
                'publication_year' => '2017',
                'stock' => 1,
                'status' => 'borrowed',
                'img' => 'assets/img/book-item-4.jpg',
                // 'created_at' => '2024-05-15 00:00:00',
            ], [
                'id' => 2,
                'user_id' => 1,
                'category_id' => 2,
                'title' => 'Tadabbur Bacaan Shalat',
                'author' => 'Ibnu Abdil Bari',
                'publisher' => 'Zaduna',
                'publication_year' => '2022',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-5.jpg',
                // 'created_at' => '2024-05-15 00:00:00',
            ], [
                'id' => 3,
                'user_id' => 1,
                'category_id' => 2,
                'title' => 'Sifat Shalat Nabi SAW',
                'author' => 'Syaikh Muhammad Nashiruddin al-Abani',
                'publisher' => 'Darul Haq',
                'publication_year' => '2016',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-3.jpg',
                // 'created_at' => '2024-05-15 00:00:00',
            ], [
                'id' => 4,
                'user_id' => 1,
                'category_id' => 2,
                'title' => 'Seni Merayu Tuhan',
                'author' => "Husein Ja far Al - Hadar",
                'publisher' => 'Mizan',
                'publication_year' => '2022',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-1.jpg',
                // 'created_at' => '2024-05-15 00:00:00',
            ], [
                'id' => 5,
                'user_id' => 1,
                'category_id' => 2,
                'title' => 'Tuhan Ada Di Hatimu',
                'author' => "Husein Ja far Al - Hadar",
                'publisher' => 'Noura Books',
                'publication_year' => '2022',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-2.jpg',
                // 'created_at' => '2024-05-15 00:00:00',
            ], [
                'id' => 6,
                'user_id' => 1,
                'category_id' => 1,
                'title' => 'You Are Loved',
                'author' => "@quranreview",
                'publisher' => 'gagasmedia',
                'publication_year' => '2022',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-6.jpg',
            ], [
                'id' => 7,
                'user_id' => 1,
                'category_id' => 1,
                'title' => 'The Principles of Power',
                'author' => "Dion Yulianto",
                'publisher' => 'Jendela Penerbit',
                'publication_year' => '2023',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-7.jpg',
            ], [
                'id' => 8,
                'user_id' => 1,
                'category_id' => 1,
                'title' => 'Terimakasih Sudah Mengatakannya',
                'author' => "Kim Yu-jin",
                'publisher' => 'Aria Media',
                'publication_year' => '2021',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-8.jpg',
            ], [
                'id' => 9,
                'user_id' => 1,
                'category_id' => 1,
                'title' => 'Seni Tinggal di Bumi',
                'author' => "Farah Qoonita",
                'publisher' => 'Kanan Publishing',
                'publication_year' => '2022',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-9.jpg',
            ], [
                'id' => 10,
                'user_id' => 1,
                'category_id' => 1,
                'title' => 'Hidup Satu Kali Lagi',
                'author' => "Farah Qoonita",
                'publisher' => 'Kanan Publishing',
                'publication_year' => '2022',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-10.jpg',
            ], [
                'id' => 11,
                'user_id' => 1,
                'category_id' => 3,
                'title' => 'Nyala Semesta',
                'author' => "Farah Qoonita",
                'publisher' => 'Kanan Publishing',
                'publication_year' => '2022',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-11.jpg',
            ], [
                'id' => 12,
                'user_id' => 1,
                'category_id' => 1,
                'title' => 'Spiritual Problem Solving',
                'author' => "Solikhin & Kang Puji Hartono",
                'publisher' => 'Pro-U Media',
                'publication_year' => '2022',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-12.jpg',
            ],[
                'id' => 13,
                'user_id' => 1,
                'category_id' => 3,
                'title' => 'Melipat Undangan Pernikahan',
                'author' => "Mia Adam",
                'publisher' => 'Salam Solution',
                'publication_year' => '2020',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-13.jpg',
            ],[
                'id' => 14,
                'user_id' => 1,
                'category_id' => 1,
                'title' => 'Seni Mengelola Konflik',
                'author' => "Mohammad Takdir",
                'publisher' => 'Noktah',
                'publication_year' => '2020',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-14.jpg',
            ],[
                'id' => 16,
                'user_id' => 1,
                'category_id' => 2,
                'title' => 'The Day after You Die',
                'author' => "Abu Bassam Oemar Mita",
                'publisher' => 'Zaduna',
                'publication_year' => '2020',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-16.jpg',
            ],[
                'id' => 17,
                'user_id' => 1,
                'category_id' => 1,
                'title' => 'Give The Best',
                'author' => "Solikhin Abu Izzuddin",
                'publisher' => 'Era Adicitra Inermedia',
                'publication_year' => '2020',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-17.jpg',
            ],[
                'id' => 18,
                'user_id' => 1,
                'category_id' => 3,
                'title' => 'Matahari',
                'author' => "Tere Liye",
                'publisher' => 'Sabakgrip',
                'publication_year' => '2020',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-18.jpg',
            ],[
                'id' => 19,
                'user_id' => 1,
                'category_id' => 3,
                'title' => 'Bintang',
                'author' => "Tere Liye",
                'publisher' => 'Sabakgrip',
                'publication_year' => '2020',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-19.jpg',
            ],[
                'id' => 20,
                'user_id' => 1,
                'category_id' => 3,
                'title' => 'Bulan',
                'author' => "Tere Liye",
                'publisher' => 'Sabakgrip',
                'publication_year' => '2020',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-20.jpg',
            ],[
                'id' => 21,
                'user_id' => 1,
                'category_id' => 1,
                'title' => 'Loneliness is my best friend',
                'author' => "Alvi Syahrin",
                'publisher' => 'Alvi Ardi Publishing',
                'publication_year' => '2022',
                'stock' => 1,
                'status' => 'available',
                'img' => 'assets/img/book-item-21.jpg',
            ],
        ];

        Book::insert($books);
    }
}
